package spring.tutorial.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-28T20:01:27.201-03:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "IBankAccountServiceService", 
                  wsdlLocation = "file:/home/marcelo/git/spring-web-services/webserviceclient/src/main/resources/IBankAccountService.wsdl",
                  targetNamespace = "http://webservice.tutorial.spring/") 
public class IBankAccountServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.tutorial.spring/", "IBankAccountServiceService");
    public final static QName IBankAccountServicePort = new QName("http://webservice.tutorial.spring/", "IBankAccountServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/marcelo/git/spring-web-services/webserviceclient/src/main/resources/IBankAccountService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IBankAccountServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/marcelo/git/spring-web-services/webserviceclient/src/main/resources/IBankAccountService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IBankAccountServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IBankAccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBankAccountServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IBankAccountServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IBankAccountServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IBankAccountServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IBankAccountService
     */
    @WebEndpoint(name = "IBankAccountServicePort")
    public IBankAccountService getIBankAccountServicePort() {
        return super.getPort(IBankAccountServicePort, IBankAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBankAccountService
     */
    @WebEndpoint(name = "IBankAccountServicePort")
    public IBankAccountService getIBankAccountServicePort(WebServiceFeature... features) {
        return super.getPort(IBankAccountServicePort, IBankAccountService.class, features);
    }

}
